// ============================================================
// KPI UX Performance Tracker — Realistic Mock Data
// 4 products, 14 projects
// Junior: higher rework | Senior: high throughput, lower connection
// Líder: best precision and quality
// ============================================================

import type { Project, RoleData } from "./types";

const emptyRole = (): RoleData => ({
  participated: false,
  designHours: 0,
  adjustmentHours: 0,
  connectionHours: 0,
  fileOrgHours: 0,
  participatedInResearch: false,
  researchHours: 0,
  researchTypes: [],
  mainViews: 0,
  responsiveViews: 0,
  extraStateViews: 0,
  correctedViews: 0,
  totalAssignedViews: 0,
  connectedViews: 0,
  revisionsReceived: 0,
  qualityScore: 0,
  deliveredOnTime: false,
  observations: "",
  blockers: "",
  dependencies: "",
});

export const MOCK_PROJECTS: Project[] = [
  // ─────────────────────────────────────────────
  // PRODUCTO: Simon App (Mobile)
  // ─────────────────────────────────────────────
  {
    id: "proj_001",
    createdAt: "2024-08-01T09:00:00Z",
    updatedAt: "2024-08-20T17:00:00Z",
    productName: "Simon App",
    projectName: "Onboarding V2",
    flowName: "Registro y activación",
    startDate: "2024-08-01",
    endDate: "2024-08-20",
    platform: "Mobile",
    complexity: "Alta",
    workType: "Nuevo flujo",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 18,
        adjustmentHours: 8,
        connectionHours: 3,
        fileOrgHours: 2,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 12,
        responsiveViews: 10,
        extraStateViews: 6,
        correctedViews: 7,
        totalAssignedViews: 28,
        connectedViews: 20,
        revisionsReceived: 4,
        qualityScore: 7,
        deliveredOnTime: true,
        observations: "Primer proyecto de alta complejidad",
        blockers: "Falta de especificaciones iniciales",
        dependencies: "Definición de componentes por Líder",
      },
      "Senior": {
        participated: true,
        designHours: 14,
        adjustmentHours: 4,
        connectionHours: 5,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 6,
        researchTypes: ["entrevista", "análisis"],
        mainViews: 15,
        responsiveViews: 12,
        extraStateViews: 4,
        correctedViews: 3,
        totalAssignedViews: 31,
        connectedViews: 25,
        revisionsReceived: 2,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "Lideró estructura de flujo",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 6,
        adjustmentHours: 2,
        connectionHours: 3,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 8,
        researchTypes: ["definición funcional", "benchmark"],
        mainViews: 5,
        responsiveViews: 4,
        extraStateViews: 2,
        correctedViews: 0,
        totalAssignedViews: 11,
        connectedViews: 11,
        revisionsReceived: 1,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "Definición de sistema y guías",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 18, newComponents: 6, totalComponents: 24 },
    totalRealHours: 83,
    totalEstimatedHours: 70,
    generalNotes: "Proyecto exitoso. Retrabajo del Junior fue por especificaciones tardías.",
  },
  {
    id: "proj_002",
    createdAt: "2024-09-02T09:00:00Z",
    updatedAt: "2024-09-18T17:00:00Z",
    productName: "Simon App",
    projectName: "Mapa de rastreo",
    flowName: "Vista de mapa en tiempo real",
    startDate: "2024-09-02",
    endDate: "2024-09-18",
    platform: "Mobile",
    complexity: "Alta",
    workType: "Nuevo flujo",
    status: "Aprobado",
    roles: {
      "Junior": {
        ...emptyRole(),
        participated: false,
      },
      "Senior": {
        participated: true,
        designHours: 20,
        adjustmentHours: 5,
        connectionHours: 6,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 5,
        researchTypes: ["benchmark", "análisis"],
        mainViews: 18,
        responsiveViews: 0,
        extraStateViews: 8,
        correctedViews: 4,
        totalAssignedViews: 26,
        connectedViews: 20,
        revisionsReceived: 2,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "Diseño complejo de mapa",
        blockers: "API de mapas definida tarde",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 8,
        adjustmentHours: 2,
        connectionHours: 3,
        fileOrgHours: 1,
        participatedInResearch: true,
        researchHours: 6,
        researchTypes: ["definición funcional", "entrevista"],
        mainViews: 6,
        responsiveViews: 0,
        extraStateViews: 3,
        correctedViews: 0,
        totalAssignedViews: 9,
        connectedViews: 9,
        revisionsReceived: 1,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 12, newComponents: 8, totalComponents: 20 },
    totalRealHours: 63,
    totalEstimatedHours: 60,
    generalNotes: "Proyecto técnicamente complejo. La conexión de flujos fue el mayor reto.",
  },
  {
    id: "proj_003",
    createdAt: "2024-10-07T09:00:00Z",
    updatedAt: "2024-10-22T17:00:00Z",
    productName: "Simon App",
    projectName: "Notificaciones push",
    flowName: "Alertas y preferencias",
    startDate: "2024-10-07",
    endDate: "2024-10-22",
    platform: "Mobile",
    complexity: "Media",
    workType: "Mejora",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 12,
        adjustmentHours: 5,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 8,
        responsiveViews: 6,
        extraStateViews: 4,
        correctedViews: 4,
        totalAssignedViews: 18,
        connectedViews: 14,
        revisionsReceived: 3,
        qualityScore: 7,
        deliveredOnTime: false,
        observations: "Tardó más de lo esperado en estados negativos",
        blockers: "Cambios de requerimientos en semana 2",
        dependencies: "",
      },
      "Senior": {
        participated: true,
        designHours: 10,
        adjustmentHours: 3,
        connectionHours: 4,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 10,
        responsiveViews: 8,
        extraStateViews: 4,
        correctedViews: 2,
        totalAssignedViews: 22,
        connectedViews: 18,
        revisionsReceived: 1,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": emptyRole(),
    },
    designSystem: { reusedComponents: 16, newComponents: 2, totalComponents: 18 },
    totalRealHours: 38,
    totalEstimatedHours: 35,
    generalNotes: "Cambio de requerimientos impactó al Junior.",
  },

  // ─────────────────────────────────────────────
  // PRODUCTO: Portal Empresas (Web)
  // ─────────────────────────────────────────────
  {
    id: "proj_004",
    createdAt: "2024-07-01T09:00:00Z",
    updatedAt: "2024-07-25T17:00:00Z",
    productName: "Portal Empresas",
    projectName: "Dashboard de flota",
    flowName: "Vista general y filtros",
    startDate: "2024-07-01",
    endDate: "2024-07-25",
    platform: "Web",
    complexity: "Alta",
    workType: "Nuevo flujo",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 16,
        adjustmentHours: 9,
        connectionHours: 2,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 3,
        researchTypes: ["revisión de hallazgos"],
        mainViews: 10,
        responsiveViews: 8,
        extraStateViews: 5,
        correctedViews: 6,
        totalAssignedViews: 23,
        connectedViews: 16,
        revisionsReceived: 4,
        qualityScore: 6,
        deliveredOnTime: false,
        observations: "Dashboard complejo para primera vez en web",
        blockers: "Sin acceso a datos reales del API",
        dependencies: "Definición de métricas por producto",
      },
      "Senior": {
        participated: true,
        designHours: 18,
        adjustmentHours: 4,
        connectionHours: 5,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 7,
        researchTypes: ["entrevista", "análisis", "benchmark"],
        mainViews: 20,
        responsiveViews: 15,
        extraStateViews: 6,
        correctedViews: 3,
        totalAssignedViews: 41,
        connectedViews: 33,
        revisionsReceived: 2,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 8,
        adjustmentHours: 2,
        connectionHours: 4,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 10,
        researchTypes: ["definición funcional", "entrevista", "benchmark"],
        mainViews: 8,
        responsiveViews: 6,
        extraStateViews: 3,
        correctedViews: 0,
        totalAssignedViews: 17,
        connectedViews: 17,
        revisionsReceived: 1,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "Definición de KPIs y estructura de datos",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 20, newComponents: 12, totalComponents: 32 },
    totalRealHours: 103,
    totalEstimatedHours: 85,
    generalNotes: "Proyecto más complejo del trimestre. Subestimado por falta de histórico en web.",
  },
  {
    id: "proj_005",
    createdAt: "2024-09-10T09:00:00Z",
    updatedAt: "2024-09-28T17:00:00Z",
    productName: "Portal Empresas",
    projectName: "Gestión de conductores",
    flowName: "CRUD y perfiles",
    startDate: "2024-09-10",
    endDate: "2024-09-28",
    platform: "Web",
    complexity: "Media",
    workType: "Nuevo flujo",
    status: "Entregado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 14,
        adjustmentHours: 5,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 10,
        responsiveViews: 8,
        extraStateViews: 4,
        correctedViews: 4,
        totalAssignedViews: 22,
        connectedViews: 17,
        revisionsReceived: 3,
        qualityScore: 7,
        deliveredOnTime: true,
        observations: "Mejoró en conexión vs proyectos anteriores",
        blockers: "",
        dependencies: "",
      },
      "Senior": {
        participated: true,
        designHours: 12,
        adjustmentHours: 3,
        connectionHours: 4,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 12,
        responsiveViews: 10,
        extraStateViews: 4,
        correctedViews: 2,
        totalAssignedViews: 26,
        connectedViews: 22,
        revisionsReceived: 1,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": emptyRole(),
    },
    designSystem: { reusedComponents: 18, newComponents: 4, totalComponents: 22 },
    totalRealHours: 45,
    totalEstimatedHours: 48,
    generalNotes: "Proyecto dentro de estimación. Junior con mejora visible.",
  },
  {
    id: "proj_006",
    createdAt: "2024-11-04T09:00:00Z",
    updatedAt: "2024-11-18T17:00:00Z",
    productName: "Portal Empresas",
    projectName: "Reportes de ruta",
    flowName: "Exportación y filtros",
    startDate: "2024-11-04",
    endDate: "2024-11-18",
    platform: "Web",
    complexity: "Media",
    workType: "Mejora",
    status: "Aprobado",
    roles: {
      "Junior": emptyRole(),
      "Senior": {
        participated: true,
        designHours: 14,
        adjustmentHours: 3,
        connectionHours: 4,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 14,
        responsiveViews: 10,
        extraStateViews: 5,
        correctedViews: 2,
        totalAssignedViews: 29,
        connectedViews: 25,
        revisionsReceived: 1,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "Flujo bien estructurado desde el inicio",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 4,
        adjustmentHours: 1,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: true,
        researchHours: 4,
        researchTypes: ["definición funcional"],
        mainViews: 4,
        responsiveViews: 3,
        extraStateViews: 1,
        correctedViews: 0,
        totalAssignedViews: 8,
        connectedViews: 8,
        revisionsReceived: 0,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "Revisión final y sign-off",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 22, newComponents: 2, totalComponents: 24 },
    totalRealHours: 34,
    totalEstimatedHours: 36,
    generalNotes: "Dentro de estimación. Proyecto ejecutado sin Júnior por carga.",
  },

  // ─────────────────────────────────────────────
  // PRODUCTO: Simon Fleet (Ambos)
  // ─────────────────────────────────────────────
  {
    id: "proj_007",
    createdAt: "2024-06-03T09:00:00Z",
    updatedAt: "2024-06-28T17:00:00Z",
    productName: "Simon Fleet",
    projectName: "Alertas de telemetría",
    flowName: "Configuración y umbrales",
    startDate: "2024-06-03",
    endDate: "2024-06-28",
    platform: "Ambos",
    complexity: "Alta",
    workType: "Nuevo flujo",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 20,
        adjustmentHours: 10,
        connectionHours: 3,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 4,
        researchTypes: ["análisis"],
        mainViews: 12,
        responsiveViews: 10,
        extraStateViews: 6,
        correctedViews: 8,
        totalAssignedViews: 28,
        connectedViews: 19,
        revisionsReceived: 5,
        qualityScore: 6,
        deliveredOnTime: false,
        observations: "Mayor retrabajo del año para este rol",
        blockers: "Requerimientos técnicos poco claros",
        dependencies: "Definición de alertas por equipo de producto",
      },
      "Senior": {
        participated: true,
        designHours: 16,
        adjustmentHours: 5,
        connectionHours: 6,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 8,
        researchTypes: ["entrevista", "análisis", "benchmark"],
        mainViews: 16,
        responsiveViews: 14,
        extraStateViews: 8,
        correctedViews: 4,
        totalAssignedViews: 38,
        connectedViews: 30,
        revisionsReceived: 2,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "Throughput alto pero conexión cayó vs promedio",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 8,
        adjustmentHours: 2,
        connectionHours: 4,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 10,
        researchTypes: ["definición funcional", "entrevista", "revisión de hallazgos"],
        mainViews: 6,
        responsiveViews: 5,
        extraStateViews: 2,
        correctedViews: 0,
        totalAssignedViews: 13,
        connectedViews: 13,
        revisionsReceived: 1,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "Carga alta de investigación justificada por complejidad",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 14, newComponents: 14, totalComponents: 28 },
    totalRealHours: 122,
    totalEstimatedHours: 100,
    generalNotes: "Proyecto más subestimado. Plataforma doble + alta complejidad técnica.",
  },
  {
    id: "proj_008",
    createdAt: "2024-08-12T09:00:00Z",
    updatedAt: "2024-08-30T17:00:00Z",
    productName: "Simon Fleet",
    projectName: "Panel de conductor",
    flowName: "Vista de turno y métricas",
    startDate: "2024-08-12",
    endDate: "2024-08-30",
    platform: "Mobile",
    complexity: "Media",
    workType: "Nuevo flujo",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 10,
        adjustmentHours: 4,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 8,
        responsiveViews: 6,
        extraStateViews: 3,
        correctedViews: 3,
        totalAssignedViews: 17,
        connectedViews: 13,
        revisionsReceived: 3,
        qualityScore: 7,
        deliveredOnTime: true,
        observations: "Leve mejora en retrabajo vs trimestre anterior",
        blockers: "",
        dependencies: "",
      },
      "Senior": {
        participated: true,
        designHours: 12,
        adjustmentHours: 3,
        connectionHours: 4,
        fileOrgHours: 1,
        participatedInResearch: true,
        researchHours: 5,
        researchTypes: ["entrevista"],
        mainViews: 12,
        responsiveViews: 0,
        extraStateViews: 5,
        correctedViews: 2,
        totalAssignedViews: 17,
        connectedViews: 14,
        revisionsReceived: 1,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": emptyRole(),
    },
    designSystem: { reusedComponents: 14, newComponents: 3, totalComponents: 17 },
    totalRealHours: 42,
    totalEstimatedHours: 45,
    generalNotes: "Proyecto bien ejecutado. Junior muestra progreso.",
  },
  {
    id: "proj_009",
    createdAt: "2024-10-14T09:00:00Z",
    updatedAt: "2024-10-30T17:00:00Z",
    productName: "Simon Fleet",
    projectName: "Ranking de conductores",
    flowName: "Gamificación y logros",
    startDate: "2024-10-14",
    endDate: "2024-10-30",
    platform: "Ambos",
    complexity: "Media",
    workType: "Nuevo flujo",
    status: "Requiere ajustes",
    roles: {
      "Junior": {
        participated: true,
        designHours: 12,
        adjustmentHours: 6,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 10,
        responsiveViews: 8,
        extraStateViews: 4,
        correctedViews: 5,
        totalAssignedViews: 22,
        connectedViews: 16,
        revisionsReceived: 4,
        qualityScore: 7,
        deliveredOnTime: false,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Senior": {
        participated: true,
        designHours: 10,
        adjustmentHours: 4,
        connectionHours: 5,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 12,
        responsiveViews: 10,
        extraStateViews: 5,
        correctedViews: 3,
        totalAssignedViews: 27,
        connectedViews: 22,
        revisionsReceived: 2,
        qualityScore: 7,
        deliveredOnTime: false,
        observations: "Estado de ajustes pendiente por diseño de logros",
        blockers: "Definición de mecánicas de gamificación incompleta",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 4,
        adjustmentHours: 1,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: true,
        researchHours: 5,
        researchTypes: ["benchmark", "análisis"],
        mainViews: 3,
        responsiveViews: 2,
        extraStateViews: 1,
        correctedViews: 0,
        totalAssignedViews: 6,
        connectedViews: 6,
        revisionsReceived: 0,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 12, newComponents: 6, totalComponents: 18 },
    totalRealHours: 53,
    totalEstimatedHours: 50,
    generalNotes: "Proyecto en revisión por falta de definición de mecánicas.",
  },

  // ─────────────────────────────────────────────
  // PRODUCTO: Simon Admin (Web)
  // ─────────────────────────────────────────────
  {
    id: "proj_010",
    createdAt: "2024-05-06T09:00:00Z",
    updatedAt: "2024-05-24T17:00:00Z",
    productName: "Simon Admin",
    projectName: "Gestión de cuentas",
    flowName: "Crear, editar y suspender cuentas",
    startDate: "2024-05-06",
    endDate: "2024-05-24",
    platform: "Web",
    complexity: "Baja",
    workType: "Copia/adaptación",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 8,
        adjustmentHours: 3,
        connectionHours: 1,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 6,
        responsiveViews: 5,
        extraStateViews: 3,
        correctedViews: 2,
        totalAssignedViews: 14,
        connectedViews: 11,
        revisionsReceived: 2,
        qualityScore: 7,
        deliveredOnTime: true,
        observations: "Proyecto de bajo esfuerzo, buena ejecución",
        blockers: "",
        dependencies: "",
      },
      "Senior": emptyRole(),
      "Líder UX": {
        participated: true,
        designHours: 3,
        adjustmentHours: 1,
        connectionHours: 1,
        fileOrgHours: 0,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 3,
        responsiveViews: 2,
        extraStateViews: 1,
        correctedViews: 0,
        totalAssignedViews: 6,
        connectedViews: 6,
        revisionsReceived: 0,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "Solo revisión y sign-off",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 16, newComponents: 1, totalComponents: 17 },
    totalRealHours: 18,
    totalEstimatedHours: 20,
    generalNotes: "Proyecto simple. Adaptación de flujo existente.",
  },
  {
    id: "proj_011",
    createdAt: "2024-06-17T09:00:00Z",
    updatedAt: "2024-07-04T17:00:00Z",
    productName: "Simon Admin",
    projectName: "Módulo de facturación",
    flowName: "Generación y descarga de facturas",
    startDate: "2024-06-17",
    endDate: "2024-07-04",
    platform: "Web",
    complexity: "Alta",
    workType: "Nuevo flujo",
    status: "Aprobado",
    roles: {
      "Junior": emptyRole(),
      "Senior": {
        participated: true,
        designHours: 16,
        adjustmentHours: 4,
        connectionHours: 5,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 6,
        researchTypes: ["análisis", "definición funcional"],
        mainViews: 16,
        responsiveViews: 12,
        extraStateViews: 6,
        correctedViews: 3,
        totalAssignedViews: 34,
        connectedViews: 28,
        revisionsReceived: 2,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 6,
        adjustmentHours: 2,
        connectionHours: 3,
        fileOrgHours: 2,
        participatedInResearch: true,
        researchHours: 8,
        researchTypes: ["entrevista", "definición funcional", "revisión de hallazgos"],
        mainViews: 5,
        responsiveViews: 4,
        extraStateViews: 2,
        correctedViews: 0,
        totalAssignedViews: 11,
        connectedViews: 11,
        revisionsReceived: 1,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "Coordinación con legal y producto para definición de flujo",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 20, newComponents: 8, totalComponents: 28 },
    totalRealHours: 54,
    totalEstimatedHours: 55,
    generalNotes: "Dentro de estimación. Buen desempeño del Senior en flujo complejo.",
  },
  {
    id: "proj_012",
    createdAt: "2024-08-26T09:00:00Z",
    updatedAt: "2024-09-06T17:00:00Z",
    productName: "Simon Admin",
    projectName: "Configuración de roles",
    flowName: "Permisos y accesos",
    startDate: "2024-08-26",
    endDate: "2024-09-06",
    platform: "Web",
    complexity: "Baja",
    workType: "Ajuste",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 6,
        adjustmentHours: 2,
        connectionHours: 1,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 4,
        responsiveViews: 3,
        extraStateViews: 2,
        correctedViews: 1,
        totalAssignedViews: 9,
        connectedViews: 7,
        revisionsReceived: 1,
        qualityScore: 7.5,
        deliveredOnTime: true,
        observations: "Ejecución limpia en proyecto pequeño",
        blockers: "",
        dependencies: "",
      },
      "Senior": emptyRole(),
      "Líder UX": emptyRole(),
    },
    designSystem: { reusedComponents: 12, newComponents: 1, totalComponents: 13 },
    totalRealHours: 10,
    totalEstimatedHours: 12,
    generalNotes: "Micro-proyecto. Junior ejecutó solo con éxito.",
  },
  {
    id: "proj_013",
    createdAt: "2024-11-11T09:00:00Z",
    updatedAt: "2024-11-30T17:00:00Z",
    productName: "Simon Admin",
    projectName: "Panel de auditoría",
    flowName: "Log de actividad y exportación",
    startDate: "2024-11-11",
    endDate: "2024-11-30",
    platform: "Web",
    complexity: "Media",
    workType: "Nuevo flujo",
    status: "Entregado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 10,
        adjustmentHours: 4,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: true,
        researchHours: 2,
        researchTypes: ["revisión de hallazgos"],
        mainViews: 7,
        responsiveViews: 6,
        extraStateViews: 3,
        correctedViews: 3,
        totalAssignedViews: 16,
        connectedViews: 12,
        revisionsReceived: 2,
        qualityScore: 7.5,
        deliveredOnTime: true,
        observations: "Mejor que proyectos anteriores en conexión",
        blockers: "",
        dependencies: "",
      },
      "Senior": {
        participated: true,
        designHours: 12,
        adjustmentHours: 3,
        connectionHours: 4,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 10,
        responsiveViews: 8,
        extraStateViews: 4,
        correctedViews: 1,
        totalAssignedViews: 22,
        connectedViews: 20,
        revisionsReceived: 1,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": {
        participated: true,
        designHours: 3,
        adjustmentHours: 1,
        connectionHours: 1,
        fileOrgHours: 1,
        participatedInResearch: true,
        researchHours: 4,
        researchTypes: ["definición funcional"],
        mainViews: 2,
        responsiveViews: 2,
        extraStateViews: 1,
        correctedViews: 0,
        totalAssignedViews: 5,
        connectedViews: 5,
        revisionsReceived: 0,
        qualityScore: 9,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
    },
    designSystem: { reusedComponents: 18, newComponents: 3, totalComponents: 21 },
    totalRealHours: 48,
    totalEstimatedHours: 46,
    generalNotes: "Junior muestra mejora sostenida. Equipo completo bien coordinado.",
  },
  {
    id: "proj_014",
    createdAt: "2024-12-02T09:00:00Z",
    updatedAt: "2024-12-18T17:00:00Z",
    productName: "Simon App",
    projectName: "Historial de viajes",
    flowName: "Lista, detalle y filtros",
    startDate: "2024-12-02",
    endDate: "2024-12-18",
    platform: "Mobile",
    complexity: "Media",
    workType: "Mejora",
    status: "Aprobado",
    roles: {
      "Junior": {
        participated: true,
        designHours: 8,
        adjustmentHours: 3,
        connectionHours: 2,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 7,
        responsiveViews: 5,
        extraStateViews: 3,
        correctedViews: 2,
        totalAssignedViews: 15,
        connectedViews: 12,
        revisionsReceived: 2,
        qualityScore: 8,
        deliveredOnTime: true,
        observations: "Buen desempeño al cierre del año",
        blockers: "",
        dependencies: "",
      },
      "Senior": {
        participated: true,
        designHours: 10,
        adjustmentHours: 2,
        connectionHours: 3,
        fileOrgHours: 1,
        participatedInResearch: false,
        researchHours: 0,
        researchTypes: [],
        mainViews: 10,
        responsiveViews: 8,
        extraStateViews: 4,
        correctedViews: 1,
        totalAssignedViews: 22,
        connectedViews: 20,
        revisionsReceived: 1,
        qualityScore: 8.5,
        deliveredOnTime: true,
        observations: "",
        blockers: "",
        dependencies: "",
      },
      "Líder UX": emptyRole(),
    },
    designSystem: { reusedComponents: 16, newComponents: 2, totalComponents: 18 },
    totalRealHours: 30,
    totalEstimatedHours: 30,
    generalNotes: "Estimación exacta. Equipo maduro en este tipo de proyecto.",
  },
];
